apiVersion: v1
kind: Service
metadata:
  name: svc-configurationworker
  labels:
    version: dev
    product: configurationworker
spec:
  selector:
    app: configurationworker
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: svc-configurationworker
  labels:
    version: dev
    product: configurationworker
spec:
  selector:
    app: configurationworker
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-configurationworker
spec:
  selector:
    matchLabels:
      app : configurationworker
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configurationworker
    spec:
      volumes:
      - name: secretsettings
        secret:
          secretName: secret-appsettings
      containers:
      - name: configurationworker
        terminationMessagePath: "/tmp/gamingwebapp-log"
        image: configurationworker:latest
        imagePullPolicy: Never
        env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        - name: Worker__DelayInMilliSeconds
          value: "5000"
        - name: ApplicationInsights__InstrumentationKey
          value: <your-instrumentation-key>
        - name: ConnectionStrings__AppConfig
          valueFrom:
            secretKeyRef:
              name: appconfig-secret
              key: connection_string
              optional: false 
        ports:
        - containerPort: 80
        - containerPort: 443
        # volumeMounts:
        # - name: secretsettings
        #   mountPath: /app/secrets
        #   readOnly: true
        resources:
          limits:
            cpu: "0.10"