version: '3.4'

services:
  containerconfiguration:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Worker__DelayInMilliSeconds=5000
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro